@startuml actors
actor "Guest User" as Guest
actor "Registered User" as User
actor "Auction Owner" as Owner
actor "Bidder" as Bidder
actor "Administrator" as Admin
actor "OAuth2 API" as Api
actor "User" as SUser
actor "System (Scheduler)" as System

SUser <|-- User
User <|-- Owner
User <|-- Bidder
SUser <|-- Guest

@enduml