@startuml actors
actor "Authenticated User" as User
actor "Auction Owner" as Owner
actor "Bidder" as Bidder
actor "Administrator" as Admin
actor "User" as SUser
actor "Guest User" as Guest
SUser <|-- User
User <|-- Owner
User <|-- Bidder
SUser <|-- Admin
SUser <|-- Guest

@enduml