@startuml
skinparam groupInheritance 2

entity Account {
  {field}Username : varchar (not null)
  {field}Email : varchar (not null)
  {field}Password : varchar (not null)
  {field}Registration_Date : date (not null)
  Profile_Picture : varchar
  Birth_Date : date
  Address : varchar
}

entity User {
}

entity Admin {
}

entity Auction {
  {field}Title : varchar (not null)
  Description : varchar
  {field}Start_Date : date (not null)
  {field}End_Date : date (not null, >= Start_Date + 1 day)
  Status : enum
  {field}Current_Bid : decimal (>= Minimum_Bid)
  Minimum_Bid : decimal
}

entity Category {
  {field}Category_Name : varchar (not null)
}

entity Bid {
  {field}Bid_Amount : decimal (not null)
  {field}Bid_Time : datetime (not null)
}

entity Rating {
  {field}Rating_Score : int (not null, >=0 and <=5)
  Rating_Comment : text
  Rating_Date : date
}

entity Comment {
  {field}Comment_Text : text (not null)
  {field}Comment_Date : datetime (nt null)
}

entity Report {
  {field}Report_Reason : text (not null)
  {field}Report_Date : date (not null)
  Status : enum
}

entity Notification {
  {field}Notification_Text : text (not null)
  {field}Notification_Date : datetime (not null)
  Notification_Type : enum
}

entity Transaction {
  {field}Amount : decimal (not null)
  {field}Transaction_Date : date (not null)
}

Account <|-- User
Account <|-- Admin
User "1" -- "0..*" Auction : creates
Auction "1" -- "0..*" Bid : receives
User "1" -- "0..*" Bid : places
Auction "1" -- "0..*" Comment : receives
User "1" -- "0..*" Comment : writes
Category "1" -- "0..*" Auction : categorizes
Auction "1" -- "0..*" Rating : is_rated_on
User "1" -- "0..*" Rating : gives
User "1" -- "0..*" Rating : receives
Auction "1" -- "0..*" Report : has_report
User "1" -- "0..*" Report : reports
User "1" -- "0..*" Notification : receives
Auction "1" -- "0..1" Transaction : results_in
User "1" -- "0..*" Transaction : buys/sells

@enduml
