@startuml sitemap
left to right direction

' Definir a Homepage fora de qualquer pacote
[Homepage (UI01)]

package "Static Pages" {
    [About (UI02)] --> [Homepage (UI01)]
    [Services (UI03)] --> [Homepage (UI01)]
    [FAQ (UI04)] --> [Homepage (UI01)]
    [Contact Us (UI05)] --> [Homepage (UI01)]
}

package "User Pages" {
    [Login (UI06)] --> [Homepage (UI01)]
    [Registration (UI07)] --> [Homepage (UI01)]
    [Password Recovery (UI08)] --> [Homepage (UI01)]
    collections "User Profile (UI09)" as prof
    prof --> [Homepage (UI01)]
    [Edit Profile (UI10)] --> prof
    [Followed Auctions (UI11)] --> prof
    [Add Credit (UI12)] --> prof
    [Create Auction (UI13)] --> prof
}

package "Admin Pages" {
    [Administration (UI14)] --> [Homepage (UI01)]
    [Manage Auctions (UI15)] --> [Administration (UI14)]
    [Manage Reports (UI16)] --> [Administration (UI14)]
    [Category Management (UI17)] --> [Administration (UI14)]
    [User Management (UI18)] --> [Administration (UI14)]
}

package "Auction Library" {
    collections "View Auction (UI19)" as icat
    collections "View Category (UI20)" as vcat
    vcat --> [Homepage (UI01)]
    icat --> [Homepage (UI01)]
    [Search (UI21)] --> [Homepage (UI01)]
    [Auction Details (UI22)] --> icat
    [Bidding History (UI23)] as bid_hist 
    bid_hist --> icat
    [Report (UI24)] --> icat
}

package "Auction Owner Pages" {
    collections "My Auctions (UI25)" as myauc
    myauc --> prof
    [Edit Auction (UI26)] --> myauc
    [Manage Auction Status (UI27)] --> myauc
    [Cancel Auction (UI28)] --> myauc
    [Auction Management (UI29)] --> myauc
}

package "Bidder Pages" {
    [View Auction Bidding History (UI30)] --> icat
    [Bid on Auction (UI31)] --> icat
}

@enduml
